class Autogenerated {
  Entities? entities;

  Autogenerated({this.entities});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    entities = json['entities'] != null
        ? new Entities.fromJson(json['entities'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.entities != null) {
      data['entities'] = this.entities!.toJson();
    }
    return data;
  }
}

class Entities {
  List<GovernmentGovernment>? governmentGovernment;
  List<LicenseNumberLicenseNumber>? licenseNumberLicenseNumber;
  List<LicenseTypeLicenseType>? licenseTypeLicenseType;

  Entities(
      {this.governmentGovernment,
        this.licenseNumberLicenseNumber,
        this.licenseTypeLicenseType});

  Entities.fromJson(Map<String, dynamic> json) {
    if (json['government:government'] != null) {
      governmentGovernment = <GovernmentGovernment>[];
      json['government:government'].forEach((v) {
        governmentGovernment!.add(new GovernmentGovernment.fromJson(v));
      });
    }
    if (json['licenseNumber:licenseNumber'] != null) {
      licenseNumberLicenseNumber = <LicenseNumberLicenseNumber>[];
      json['licenseNumber:licenseNumber'].forEach((v) {
        licenseNumberLicenseNumber!
            .add(new LicenseNumberLicenseNumber.fromJson(v));
      });
    }
    if (json['licenseType:licenseType'] != null) {
      licenseTypeLicenseType = <LicenseTypeLicenseType>[];
      json['licenseType:licenseType'].forEach((v) {
        licenseTypeLicenseType!.add(new LicenseTypeLicenseType.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.governmentGovernment != null) {
      data['government:government'] =
          this.governmentGovernment!.map((v) => v.toJson()).toList();
    }
    if (this.licenseNumberLicenseNumber != null) {
      data['licenseNumber:licenseNumber'] =
          this.licenseNumberLicenseNumber!.map((v) => v.toJson()).toList();
    }
    if (this.licenseTypeLicenseType != null) {
      data['licenseType:licenseType'] =
          this.licenseTypeLicenseType!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class GovernmentGovernment {
  double? confidence;
  String? name;
  String? value;

  GovernmentGovernment({this.confidence, this.name, this.value});

  GovernmentGovernment.fromJson(Map<String, dynamic> json) {
    confidence = json['confidence'];
    name = json['name'];
    value = json['value'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['confidence'] = this.confidence;
    data['name'] = this.name;
    data['value'] = this.value;
    return data;
  }
}

class LicenseNumberLicenseNumber {
  double? confidence;
  String? name;
  String? value;

  LicenseNumberLicenseNumber({this.confidence, this.name, this.value});

  LicenseNumberLicenseNumber.fromJson(Map<String, dynamic> json) {
    confidence = json['confidence'];
    name = json['name'];
    value = json['value'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['confidence'] = this.confidence;
    data['name'] = this.name;
    data['value'] = this.value;
    return data;
  }
}


class LicenseTypeLicenseType {
  double? confidence;
  String? name;
  String? value;

  LicenseTypeLicenseType({this.confidence, this.name, this.value});

  LicenseTypeLicenseType.fromJson(Map<String, dynamic> json) {
    confidence = json['confidence'];
    name = json['name'];
    value = json['value'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['confidence'] = this.confidence;
    data['name'] = this.name;
    data['value'] = this.value;
    return data;
  }
}

